#!/usr/bin/env node
// Replicates the canonical skill root into the generated roots.
//
//   .claude/skills/   SOURCE — the only place a skill is edited
//        ├─────────►  .agents/skills/          byte-for-byte mirror
//   CLAUDE.md         ├─────────►  AGENTS.md   contract block + skill index
//                     └─────────►  .cursor/rules/noetron.mdc
//
// Zero dependencies, Node 18+. The harness itself is markdown; this script only
// keeps the copies honest, so a consumer on any stack can run it without a
// toolchain of its own.
//
//   node scripts/sync-noetron.mjs            regenerate the mirrors
//   node scripts/sync-noetron.mjs --check    verify they match (exit 1 if not)

import { createHash } from 'node:crypto';
import { existsSync } from 'node:fs';
import { mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, join, relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

import { runOracles } from './noetron-oracles.mjs';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const SOURCE = join(ROOT, '.claude', 'skills');
const MIRROR = join(ROOT, '.agents', 'skills');
const CONTRACT_FILE = join(ROOT, 'CLAUDE.md');
const AGENTS_FILE = join(ROOT, 'AGENTS.md');
const CURSOR_RULE = join(ROOT, '.cursor', 'rules', 'noetron.mdc');

const CONTRACT_ASSET = join(
  ROOT, '.claude', 'skills', 'noetron-setup', 'assets', 'contract.md',
);

// AGENTS.md carries two blocks with two owners, and they never overlap:
//
//   noetron:contract — the standing contract. Written by noetron-setup in a
//                      consumer, verbatim from assets/contract.md. Stable.
//   noetron:index    — the skill list. Written by this script, because it is
//                      the only thing that can enumerate the skill root, and it
//                      changes every time a skill is born or retired.
//
// One block per owner is what keeps a consumer without Node usable: setup still
// anchors the contract, and only the index goes missing.
const CONTRACT_OPEN = '<!-- noetron:contract -->';
const CONTRACT_CLOSE = '<!-- /noetron:contract -->';
const INDEX_OPEN = '<!-- noetron:index -->';
const INDEX_CLOSE = '<!-- /noetron:index -->';

const GENERATED_BANNER =
  '<!-- GENERATED by scripts/sync-noetron.mjs — do NOT edit by hand.\n' +
  '     Add or remove a skill under .claude/skills/, then re-run the script. -->';

const check = process.argv.includes('--check');
const problems = [];

/** Every file under `dir`, as paths relative to it, in stable order. */
async function walk(dir, base = dir) {
  if (!existsSync(dir)) return [];
  const found = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) found.push(...(await walk(full, base)));
    else found.push(relative(base, full).split(sep).join('/'));
  }
  return found.sort();
}

const digest = (buf) => createHash('sha256').update(buf).digest('hex');

/** Writes only when content differs; in --check mode records a problem instead. */
async function emit(path, content) {
  const target = Buffer.from(content, 'utf8');
  const current = existsSync(path) ? await readFile(path) : null;
  if (current && digest(current) === digest(target)) return false;

  if (check) {
    problems.push(`out of sync: ${relative(ROOT, path).split(sep).join('/')}`);
    return false;
  }
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, target);
  return true;
}

function contractBlock(claudeMd) {
  const start = claudeMd.indexOf(CONTRACT_OPEN);
  const end = claudeMd.indexOf(CONTRACT_CLOSE);
  if (start === -1 || end === -1) {
    throw new Error(`CLAUDE.md is missing the ${CONTRACT_OPEN} markers`);
  }
  return claudeMd.slice(start + CONTRACT_OPEN.length, end).trim();
}

/** Skill folder names, from the source root. */
async function listSkills() {
  if (!existsSync(SOURCE)) throw new Error(`no skill root at ${SOURCE}`);
  const entries = await readdir(SOURCE, { withFileTypes: true });
  return entries
    .filter((e) => e.isDirectory() && existsSync(join(SOURCE, e.name, 'SKILL.md')))
    .map((e) => e.name)
    .sort();
}

/**
 * A route pointing at a skill that does not exist is worse than no route: the
 * agent follows it and lands nowhere. Cheap to check, so check every mention.
 */
async function findBrokenReferences(skills) {
  const known = new Set(skills);
  const broken = new Map();
  const files = [
    ...(await walk(SOURCE)).map((f) => join(SOURCE, f)),
    CONTRACT_FILE,
  ].filter((f) => f.endsWith('.md') && existsSync(f));

  for (const file of files) {
    const text = await readFile(file, 'utf8');
    for (const match of text.matchAll(/\bnoetron-[a-z][a-z0-9-]*/g)) {
      const name = match[0].replace(/-+$/, '');
      if (known.has(name) || name === 'noetron-contract') continue;
      const where = relative(ROOT, file).split(sep).join('/');
      if (!broken.has(name)) broken.set(name, new Set());
      broken.get(name).add(where);
    }
  }
  return broken;
}

async function syncMirror(skills) {
  const sourceFiles = await walk(SOURCE);
  let changed = 0;

  for (const rel of sourceFiles) {
    const content = await readFile(join(SOURCE, rel));
    if (await emit(join(MIRROR, rel), content.toString('utf8'))) changed++;
  }

  // A skill deleted at the source must not survive in the mirror.
  for (const rel of await walk(MIRROR)) {
    if (sourceFiles.includes(rel)) continue;
    const stale = join(MIRROR, rel);
    if (check) problems.push(`stale in mirror: .agents/skills/${rel}`);
    else {
      await rm(stale);
      changed++;
    }
  }
  return { changed, count: skills.length };
}

/** The contract block — same bytes noetron-setup anchors, markers included. */
function buildContractBlock(contract) {
  return `${CONTRACT_OPEN}\n${contract}\n${CONTRACT_CLOSE}`;
}

/** The index block — this script's own, and the only place it writes prose. */
function buildIndexBlock(skills) {
  const list = skills.map((s) => `- \`${s}\``).join('\n');
  return `${INDEX_OPEN}
${GENERATED_BANNER}

## Skill index

Skills live in \`.agents/skills/<name>/SKILL.md\`, mirrored from \`.claude/skills/\`. Read a
skill's file before following it — the index only says what exists.

${list}
${INDEX_CLOSE}`;
}

/**
 * Splices one marked block into a file, leaving every other line alone.
 *
 * A consumer's AGENTS.md carries their own content — house rules, another
 * tool's block, a legacy Noetron block. Rewriting the file whole would delete
 * all of it, which is what noetron-setup forbids ("append, never rewrite").
 *
 * The strays pass exists because of a real incident: an earlier version of this
 * script emitted the generated block WITHOUT markers. Splicing over that file
 * found no marker, appended, and left the contract duplicated. So before
 * splicing, any unmarked remnant this script previously wrote is removed —
 * recognised by its own banner, never by guessing at user prose.
 */
function spliceBlock(existing, block, open, close) {
  if (existing === null) return `${block}\n`;

  const start = existing.indexOf(open);
  const end = existing.indexOf(close);

  if (start !== -1 && end !== -1 && end > start) {
    return existing.slice(0, start) + block + existing.slice(end + close.length);
  }

  const separator = existing.endsWith('\n\n') ? '' : existing.endsWith('\n') ? '\n' : '\n\n';
  return `${existing}${separator}${block}\n`;
}

// Match the banner by its stable opening, not its full text: the wording has
// changed once already, and a detector keyed to exact prose stops recognising
// the very remnants it exists to clean.
const BANNER_PREFIX = '<!-- GENERATED by scripts/sync-noetron.mjs';

/** Drops unmarked blocks this script wrote before markers existed. */
function dropUnmarkedRemnant(existing) {
  if (existing === null) return null;
  let text = existing;

  for (;;) {
    const bannerStart = text.indexOf(BANNER_PREFIX);
    if (bannerStart === -1) return text;

    // A banner inside a marked block belongs to that block's owner.
    const openedIndex = text.lastIndexOf(INDEX_OPEN, bannerStart);
    const closedIndex = text.lastIndexOf(INDEX_CLOSE, bannerStart);
    const openedContract = text.lastIndexOf(CONTRACT_OPEN, bannerStart);
    const closedContract = text.lastIndexOf(CONTRACT_CLOSE, bannerStart);
    if (openedIndex > closedIndex || openedContract > closedContract) return text;

    // The remnant runs from the banner to whatever comes next: the first
    // marker after it, or end of file.
    const nextMarker = [
      text.indexOf(CONTRACT_OPEN, bannerStart),
      text.indexOf(INDEX_OPEN, bannerStart),
    ].filter((i) => i !== -1);
    const cutEnd = nextMarker.length ? Math.min(...nextMarker) : text.length;
    text = text.slice(0, bannerStart) + text.slice(cutEnd);
  }
}

function buildCursorRule(contract) {
  return `---
description: Noetron harness contract
alwaysApply: true
---

${GENERATED_BANNER}

${contract}
`;
}

async function main() {
  const skills = await listSkills();
  const contract = contractBlock(await readFile(CONTRACT_FILE, 'utf8'));

  const mirror = await syncMirror(skills);

  // noetron-setup names assets/contract.md as the canonical payload and `diff`
  // as its oracle. Nothing was running that diff, so the two could drift apart
  // silently while every check stayed green. Now they cannot.
  if (existsSync(CONTRACT_ASSET)) {
    const asset = contractBlock(await readFile(CONTRACT_ASSET, 'utf8'));
    if (asset !== contract) {
      problems.push(
        'contract drift: CLAUDE.md and noetron-setup/assets/contract.md differ — ' +
          'setup anchors consumers from the asset, so they must be identical',
      );
    }
  }

  // AGENTS.md is a public convention: a consumer's file may already carry their
  // own rules or another tool's block. Splice our two blocks in; never own the
  // file. The contract block is written identically by setup — same bytes from
  // either writer, so neither undoes the other.
  const existingAgents = existsSync(AGENTS_FILE)
    ? await readFile(AGENTS_FILE, 'utf8')
    : null;
  const cleaned = dropUnmarkedRemnant(existingAgents);
  const withContract = spliceBlock(
    cleaned, buildContractBlock(contract), CONTRACT_OPEN, CONTRACT_CLOSE,
  );
  await emit(
    AGENTS_FILE,
    spliceBlock(withContract, buildIndexBlock(skills), INDEX_OPEN, INDEX_CLOSE),
  );

  // The Cursor rule is generated whole: it is ours, created by us, and carries
  // nothing else.
  await emit(CURSOR_RULE, buildCursorRule(contract));

  const broken = await findBrokenReferences(skills);
  for (const [name, where] of broken) {
    problems.push(`broken reference: ${name} (in ${[...where].join(', ')})`);
  }

  // The structural oracles. A route that points nowhere was already caught
  // above; these catch the opposite and costlier shape — a promise that points
  // at something real, which nothing executes.
  problems.push(...(await runOracles({ root: ROOT, sourceRoot: SOURCE, skills })));

  if (!check) {
    console.log(
      `noetron sync: ${mirror.count} skills, ${mirror.changed} file(s) updated, ` +
        `AGENTS.md and the Cursor rule regenerated.`,
    );
  }

  // Both modes report and both modes fail. Regenerating the mirrors does not
  // make a broken promise less broken, and a defect that only `--check` prints
  // is a defect nobody running the script by hand ever sees — which is how the
  // contract-drift check spent its first release silent.
  if (problems.length) {
    console.error(`${check ? 'noetron sync check FAILED' : '\nnoetron problems found — fix these'}:`);
    for (const p of problems) console.error(`  - ${p}`);
    process.exit(1);
  }
  if (check) {
    console.log(
      `noetron sync check OK — ${skills.length} skills, mirrors current, ` +
        'writer table, routing graph and skill docs symmetric.',
    );
  }
}

main().catch((error) => {
  console.error(`noetron sync failed: ${error.message}`);
  process.exit(1);
});
